### PR TITLE
Improves names of pk_get_ontotrace_xml and pk_get_study_xml functions

### PR DESCRIPTION
**Pull request by johnbradley**
Renames pk_get_ontotrace_xml() to get_ontotrace_data().
Renames pk_get_study_xml() to get_study_data() and adds a verbose parameter to control messaging.

Fixes part of #38 and #173.

### CODE REVIEW

**Comment by johnbradley** [comment]
The code in [get_ontotrace_data](
https://github.com/phenoscape/rphenoscape/blob/f584052601a37d5b0d4876c7082d196d4e2b5712/R/pk_get_xml.R#L59-L109) builds a `queryseq` vaguely similar to what is done in [pkb_args_to_query](https://github.com/phenoscape/rphenoscape/blob/f584052601a37d5b0d4876c7082d196d4e2b5712/R/pkb_get.R#L155-L227). The code is different enough that I didn't see a simple way to update pkb_args_to_query to handle this use case.

**Review by hlapp — COMMENTED** [review]
Shouldn't we also use this to correct the `taxon` and `entity` parameter handling? Specifically, the [Ontotrace API endpoint](https://kb.phenoscape.org/apidocs/#/OntoTrace/get_ontotrace) has separate parameters for lists of IRIs, and there is no need to create OWL expressions from scratch. 

Or should that be a separate PR?

**Comment by johnbradley** [comment]
> Shouldn't we also use this to correct the taxon and entity parameter handling? Specifically, the Ontotrace API endpoint has separate parameters for lists of IRIs, and there is no need to create OWL expressions from scratch.
>
> Or should that be a separate PR?

I'm fine with fixing the parameter handling on this PR.

The [/ontotrace endpoint](https://kb.phenoscape.org/apidocs/#/OntoTrace/get_ontotrace) has __taxon_list__ and __entity_list__ parameters, but does not allow specifying a __relation__. I think this is why the code is building it's own OWL expressions.

Here is the documentation for `get_ontotrace_data()` __relation__:
https://github.com/phenoscape/rphenoscape/blob/f584052601a37d5b0d4876c7082d196d4e2b5712/R/pk_get_xml.R#L16-L19 
In `get_ontotrace_data()` the code adjusts the entity OWL expressions adding `relation_id` ("develops from" or "part of"):
https://github.com/phenoscape/rphenoscape/blob/f584052601a37d5b0d4876c7082d196d4e2b5712/R/pk_get_xml.R#L97-L104

**Comment by hlapp** [comment]
Ah yes, I missed that. @balhoff can you say what the default relation(s) is/are that applies if using the `taxon_list` and `entity_list` parameters? BTW I assume that `taxon_list` and `entity_list` must either be used together, or not at all. I.e., I can't mix an OWL expression for `entity` and a `taxon_list`, or can I?

**Comment by balhoff** [comment]
@hlapp you should be able to mix them. You can even use both `entity` and `entity_list`; the result should be the union of the resulting terms. There is no real default relation. The provided OWL expression is the subsumer for the terms you want (so in that sense the relation is subClassOf).

The purpose of the lists is to return only those terms as rows or columns. So subsumption query happens at all.

**Comment by hlapp** [comment]
@balhoff I see. So if I wanted a `part_of some <X>` subsumption, I can't use `entity_list`, instead I have to provide the OWL expression to `entity`?

**Comment by balhoff** [comment]
@hlapp that's correct. The list is for giving exact terms.

**Comment by hlapp** [comment]
> The purpose of the lists is to return only those terms as rows or columns. So subsumption query happens at all.

@balhoff is this a typo in the second sentence, i.e., did you mean to say _no subsumption query happens at all_? Meaning, giving a list is not shorthand for giving an OWL expression that's the union.

**Comment by balhoff** [comment]
@hlapp, yes that was a typo. You are correct: the list is not a shorthand for a union OWL expression; it's just exactly the list of items you want to see. This option was requested by Laura and @wdahdul.

**Comment by johnbradley** [comment]
I create another issue to handle `get_ontotrace_data()` parameter handling: #180.

**Review by hlapp — APPROVED** [review]
Looks good as fas as I can see!

**Pull request merged**
