### PR TITLE
Renames pk_get_iri to get_term_iri

### PR DESCRIPTION
**Pull request by hlapp**
This is the first step for implementing #38, removing the "pk_" prefix.

### CODE REVIEW

**Comment by johnbradley** [comment]
@hlapp This PR is now caught up with baseline-v0.3.0.

It looks like there now a couple places still referencing pk_get_iri.
https://github.com/phenoscape/rphenoscape/blob/03097ede3d87b561fd73068fe19cab960fb6135f/R/profile-semsim.R#L45
https://github.com/phenoscape/rphenoscape/blob/03097ede3d87b561fd73068fe19cab960fb6135f/tests/testthat/test-semsim.R#L95
I think they came from new changes pulled from baseline-v0.3.0.
I'm going to push a commit to fix them.

**Comment by hlapp** [comment]
Is there a reason this one doesn't run through the tests?

**Comment by johnbradley** [comment]
> Is there a reason this one doesn't run through the tests?

Yes. R-CMD-check is only setup to run on pushes to master or a PR merging into master:
https://github.com/phenoscape/rphenoscape/blob/3eccb111035548009964dddf36acb00a2752bc38/.github/workflows/check-standard.yaml#L3-L13

**Comment by hlapp** [comment]
I see. Can we wildcard the destination branch for PRs, or do we need to introduce `baseline-0.3.0` as a special case here?

**Comment by johnbradley** [comment]
>I see. Can we wildcard the destination branch for PRs, or do we need to introduce baseline-0.3.0 as a special case here?

I don't think it supports wild cards. You can remove the branches part it will test all pull requests.

**Comment by johnbradley** [comment]
@hlapp Would you like me to change the github action config to test all PRs on this branch(remove-pk-prefix)?

**Comment by johnbradley** [comment]
I have rebased remove-pk-prefix that includes the updated github actions config.

**Comment by johnbradley** [comment]
@hlapp I think this PR is ready to be merged now.

**Comment by hlapp** [comment]
I wanted to first get to a stage where we have tests succeeding. Then rebase those changes onto the baseline-0.3.0 branch, then see whether we have tests still succeeding.

**Comment by hlapp** [comment]
@johnbradley looks like have passing tests again on master! If you rebase the changes onto baseline-0.3.0 and then rebase this one against baseline, hopefully we have passing tests here too.

**Pull request merged**
