### PR TITLE
usethis::use_github_action("check-standard")

### LINKED ISSUE #149: Ensure proper working CI test, including on 0.2.x release series
CI testing used travis-ci.org, which "shut down" Dec 31, 2020. Need to migrate, either to Travis-ci.com, or another mechanism.

[rOpenSci seems to suggest GitHub actions](https://ropensci.org/technotes/2020/11/19/moving-away-travis/), and makes some good point about moving away from Travis-CI altogether. Given that Rphenoscape aspires to be part of the rOpenSci community at least in spirit, maybe this is the time to take more radical action than simply migrating to Travis-CI.com.

### PR DESCRIPTION
**Pull request by johnbradley**
Adds code changes to run tests via github actions.

The code was generated by running:
```
usethis::use_github_action("check-standard")
```

Documentation for check-standard:
https://github.com/r-lib/actions/tree/master/examples#standard-ci-workflow

See #149. Closes #149.

### CODE REVIEW

**Comment by hlapp** [comment]
@johnbradley it looks to me like in principle the GitHub Actions work, as the test failures and complaints are consistent, and seem entirely unrelated to using Github Actions?

If you can change the build matrix such that

- [ ] R 4.x (i.e., release) and R 3.6 (I think this is the last R 3.x release series) are included; and
- [ ] exclude for now ubuntu devel and Windows;

then I think we can proceed by recording the reported issues that cause test failure on the issue tracker, and merging this PR. The next step is then to see how we can fix the failures. (Title Case for the title is obviously a very easy one, but the other two I'm going to have look into.)

**Comment by johnbradley** [comment]
As currently configured this github action is only run when commits are pushed to `master` or a PR is created for the `master` branch.

**Comment by hlapp** [comment]
OK looks good. The one last adjustment I think we should make for now is not to error on warnings. One of the ones we get right now is actually in RNeXML, not here, and we're not yet submitting to CRAN anyway.

**Comment by hlapp** [comment]
OK I've created #151, #152, and #153.

**Pull request merged**
