### PR TITLE
Renames pk_get_study_list to get_studies

### PR DESCRIPTION
**Pull request by hlapp**
This is part of addressing #38 (removing the "pk_" prefix).

### CODE REVIEW

**Comment by johnbradley** [comment]
I attempted to rebase the `get_studies` branch but it ended up messy.
Some of the confusion is due to duplicate commits.


The `Renames pk_get_iri to get_term_iri` https://github.com/phenoscape/rphenoscape/commit/6301b680612bb93f809d083bf1fac59f4a6c5cfc commit is already in the `remove-pk-prefix` branch as https://github.com/phenoscape/rphenoscape/commit/0553bc8af5e3f296d9f541af2797a8e5e8ccc0ce.
I think 6301b68 should be removed.


The `Fixes case of no search filters being applied` https://github.com/phenoscape/rphenoscape/pull/126/commits/b25b56fa89d223c0f6db22f2f8209819f102c4ed commit seems to be fixed in a different way in the `remove-pk-prefix` branch as https://github.com/phenoscape/rphenoscape/commit/73b2857b99059e35581abb008ce083b3141e2980
In this branch (`get_studies`) the fix looks like this:
https://github.com/phenoscape/rphenoscape/blob/b25b56fa89d223c0f6db22f2f8209819f102c4ed/R/pkb_get.R#L161-L163
In the `remove-pk-prefix` branch the fix looks like this:
https://github.com/phenoscape/rphenoscape/blob/73b2857b99059e35581abb008ce083b3141e2980/R/pkb_get.R#L165-L168
I think b25b56f should be removed.


I think we only need 5b754fb added to the remove-pk-prefix branch.

Thoughts @hlapp ?

**Comment by hlapp** [comment]
I think it's best to start with #125. It was originally meant to be merged first onto the baseline-0.3.0 branch. So I would back out of this, then let's get #125 rebased and merged onto the 0.3.0 baseline branch, then tackle this one again.

Note that these changes may break backwards compatibility, hence the implied version increment to 0.3.x. Because this (removing all the `pk_` prefixes, every one of which will be potentially backwards incompatible) can take a while, I'm thinking we still also want working CI testing and R 4.x compatibility on the 0.2.x series. So maybe that's best to tackle first.

**Comment by johnbradley** [comment]
This branch been rebased to baseline-v0.3.0. @hlapp below are some changes I would like your feedback on.

1. The https://github.com/phenoscape/rphenoscape/commit/b25b56fa89d223c0f6db22f2f8209819f102c4ed commit was skipped because it appears to already be fixed in a slightly different way in baseline-v0.3.0:
https://github.com/phenoscape/rphenoscape/blob/57c5f16262529d81f027d4014be8ffeec45c27e6/R/pkb_get.R#L178-L180
I think the baseline-v0.3.0 fix is good, but wanted a second opinion.

2. The pkb_args_to_query() function created invalid list of named parameters when [run with the `phenotype` parameter](https://github.com/phenoscape/rphenoscape/blob/57c5f16262529d81f027d4014be8ffeec45c27e6/R/phenotypes.R#L143). This resulted in error `All components of query must be named` when testing test-phentypes.R(matching phenotypes against study filter). I fixed this by adding "phenotype" to the paramNames and ont_lookups within pkb_args_to_query().  Part of the modified pkb_args_to_query is below:
https://github.com/phenoscape/rphenoscape/blob/a7a1a66bf740ddf473e19432839402a4d23961a3/R/pkb_get.R#L146-L161
Should "phenotype" be in ont_lookups(which causes get_term_iri to be called on the value)?

3. Changes here only show the warning `No study found in database.` if the deprecated `pk_get_study_list` method is called:
https://github.com/phenoscape/rphenoscape/blob/a7a1a66bf740ddf473e19432839402a4d23961a3/R/deprecated.R#L28-L33
This a caused failure in an existing test that expected the warning. I removed the call to expect_warning. https://github.com/phenoscape/rphenoscape/blob/57c5f16262529d81f027d4014be8ffeec45c27e6/tests/testthat/test-phenotypes.R#L102-L103

**Comment by hlapp** [comment]
> * The [b25b56f](https://github.com/phenoscape/rphenoscape/commit/b25b56fa89d223c0f6db22f2f8209819f102c4ed) commit was skipped because it appears to already be fixed in a slightly different way in baseline-v0.3.0:
>   
>   I think the baseline-v0.3.0 fix is good, but wanted a second opinion.

Indeed, the baseline-v0.3.0 fix is good.

> * The pkb_args_to_query() function created invalid list of named parameters when run with the `phenotype` parameter. This resulted in error `All components of query must be named` when testing test-phentypes.R (matching phenotypes against study filter). I fixed this by adding "phenotype" to the paramNames and ont_lookups within pkb_args_to_query().

This is possibly a result of support for the `phenotype` parameter having been added after branching off. 

>   Should "phenotype" be in ont_lookups (which causes get_term_iri to be called on the value)?

I don't think it should. There is no distinct phenotype ontology or list of phenotype ontologies defined (in `pk_get_IRI.R`). (There are some, such as MP and HPO, but I am not clear on whether any of these are even loaded in a way that would permit term finding by label. Maybe @balhoff can say? FYI, the `phenotype_id` variable defined in `pk_get_IRI.R` is named deceptively and a remnant from the earliest beginnings. PATO is a phenotypic quality ontology, not a phenotype ontology.) 

> * Changes here only show the warning `No study found in database.` if the deprecated `pk_get_study_list` method is called.    This a caused failure in an existing test that expected the warning. I removed the call to expect_warning.

Yes, that's the right action. The warning was a holdover from earlier times, and there is no good reason to have to depend on it being emitted.

**Comment by johnbradley** [comment]
I updated the `pkb_args_to_query()` function removing "phenotype" from ont_lookups.

**Comment by hlapp** [comment]
Nice work, @johnbradley!

**Pull request merged**
