### PR TITLE
Removes testing on R v3, and adds testing R devel

### LINKED ISSUE #283: Some dependencies have become unavailable for R 3.x
At least two dependencies (`XML` and `evaluate`) now require R >= 4.0 and have thus become unavailable under R 3.x. (At least the `XML` dependency is a result of RNeXML, see ropensci/RNeXML#259.) This causes the tests under R 3.x to fail.

To fix this, we should drop the R 3.x tests, and require R>= 4.0.

### PR DESCRIPTION
**Pull request by hlapp**
Fixes #283.

### CODE REVIEW

**Comment by hlapp** [comment]
The question is whether we should also explicitly raise the R version requirement in `DESCRIPTION` to 4.x. In theory this is sounds like a trivial change, but I think this should nonetheless precipitate incrementing the version to 0.4.x. Otherwise, if incremented only to 0.3.1, it would signal that an automatic upgrade from 0.3.0 is OK when in reality it would break things in an R 3.x environment. Or perhaps it simply wouldn't get upgraded in that environment?

@johnbradley any thoughts either way?

**Comment by johnbradley** [comment]
I would raise the R version to 4.0. If our R3 tests failed to install dependencies something similar might happen to a user with R 3 installed. I would expect existing R3 installations to not install the new version of rphenoscape once we raise the R requirement to 4. Going with 0.4.x for our version to convey the bigger jump also sounds good since we aren't at 1.0.x yet.

**Comment by hlapp** [comment]
OK. I upgraded the required R version. I'll increment the version later once we perhaps fold a few more clean-ups into the upgrade (such as #285, and the checks also indicate some URLs that need fixing).

**Review by johnbradley — APPROVED** [review]
LGTM

**Pull request merged**
