### PR TITLE
Changes to address R CMD check and CI issues

### LINKED ISSUE #285: R docs need regenerating for some functions
Apparently the changes from #281 weren't fully propagated to documentation. R CHECK yields the following warnings:
```
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from Rd file 'get_term_iri.Rd':
get_term_iri
  Code: function(text, as, exactOnly = FALSE, nomatch = NA,
                 includeRelatedSynonyms = FALSE, verbose = FALSE)
  Docs: function(text, as, exactOnly = FALSE, nomatch = NA, verbose =
                 FALSE)
  Argument names in code not in docs:
    includeRelatedSynonyms
  Mismatches in argument names:
    Position: 5 Code: includeRelatedSynonyms Docs: verbose

Codoc mismatches from Rd file 'terms.Rd':
taxon_info
  Code: function(term, includeRelatedSynonyms = FALSE, verbose = FALSE)
  Docs: function(term, verbose = FALSE)
  Argument names in code not in docs:
    includeRelatedSynonyms
  Mismatches in argument names:
    Position: 2 Code: includeRelatedSynonyms Docs: verbose
```

### PR DESCRIPTION
**Pull request by hlapp**
Fixes #285, #286, and #287.

### CODE REVIEW

**Comment by hlapp** [comment]
Still reports <https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf> as "403 Forbidden". Perhaps that's the server blocking certain origins?

**Review by johnbradley — APPROVED** [review]
LGTM

I never realized CRAN had such strange `LICENSE` requirements.

**Comment by johnbradley** [comment]
If I use curl with a bot user agent and the posit URL I get a 403:
```
$ curl -v https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf -A "User Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" > /dev/null
...
< HTTP/1.1 403 Forbidden
```

**Comment by hlapp** [comment]
Sounds like I need to remove the link then.

**Pull request merged**
