### PR TITLE
Adds polymorphic state-capable function for symbol->label

### LINKED ISSUE #229: Fix get_char_matrix multiple state labeled output
When `get_char_matrix()` is run with the `states_as_labels=TRUE` it produces an empty string if there are more than one state. Instead if should list multiple labels. For example:
```
> nex <- pk_get_ontotrace_xml(taxon = c("Ictalurus", "Ameiurus"), entity = "fin spine")
> get_char_matrix(nex, otus_id=FALSE)[c(1,2,3),c(1,4)]
               taxa anterior distal serration of pectoral fin spine
1 Ameiurus brunneus                                               1
2    Ameiurus catus                                               1
3    Ameiurus melas                                         1 and 0
> get_char_matrix(nex, otus_id=FALSE, states_as_labels=TRUE)[c(1,2,3),c(1,4)]
               taxa anterior distal serration of pectoral fin spine
1 Ameiurus brunneus                                         present
2    Ameiurus catus                                         present
3    Ameiurus melas                                                

```
In the above example when `states_as_labels=TRUE` the `Ameiurus melas` row should contain `present and absent` for the `anterior distal serration of pectoral fin spine` column.

See https://github.com/phenoscape/rphenoscape/issues/172#issuecomment-896115719

### PR DESCRIPTION
**Pull request by hlapp**
Creates a rewritten function for translating state symbols to labels in character matrices obtained from a NeXML object. This function can handle polymorphic states,

Fixes #229.

### CODE REVIEW

**Comment by hlapp** [comment]
Unfortunately, because the KB v2 API seems to be broken right now, the tests will fail.

**Review by johnbradley — COMMENTED** [review]
The changes look good. Since this is fixing a bug could you add a test?

**Comment by hlapp** [comment]
> Since this is fixing a bug could you add a test?

Yes, indeed, done now.

**Review by johnbradley — APPROVED** [review]
LGTM

**Pull request merged**
